Repository digraphs/Digraphs, pull requests merged in 2019-07, with the labels that each got.

#223 Fix issue 222
  src/homos.c
  tst/standard/grahom.tst
Labels: bugfix

#224 Add NrSpanningTrees attribute
  doc/attr.xml
  doc/z-chap4.xml
  gap/attr.gd
  gap/attr.gi
  tst/standard/attr.tst
Labels: merge-in-to-master, new-feature

#225 Add --with-external-bliss option to unvendor bliss
  .travis.yml
  Makefile.am
  README.md
  configure.ac
  m4/ax_check_bliss.m4
  scripts/travis-build-dependencies.sh
  scripts/travis-test.sh
  src/digraphs.c
  src/homos-graphs.c
Labels: 0.15, enhancement
