Repository digraphs/Digraphs, pull requests merged in 2019-06, with the labels that each got.

#198 Use MakeString instead of C_NEW_STRING
  src/homos.c
Labels: 0.15, enhancement

#208 build: properly install warning flags
  Makefile.am
  configure.ac
  m4/ax_append_compile_flags.m4
  m4/ax_append_flag.m4
  m4/ax_check_compile_flag.m4
  m4/ax_code_coverage.m4
  m4/ax_compiler_flags_cflags.m4
  m4/ax_compiler_flags_cxxflags.m4
  m4/ax_require_defined.m4
Labels: enhancement, minor

#210 grahom: allow premature termination in homomorphism search
  doc/grahom.xml
  src/homos.c
  tst/standard/grahom.tst
Labels: enhancement

#209 utils: fix DIGRAPHS_Dir
  gap/utils.gi
Labels: enhancement, minor

#211 Improve DigraphOddGirth
  gap/attr.gi
  tst/standard/attr.tst
Labels: enhancement

#204 Add GeneralisedPetersenGraph function
  doc/exmpl.xml
  doc/z-chap2.xml
  gap/exmpl.gd
  gap/exmpl.gi
  tst/standard/exmpl.tst
Labels: new-feature

#214 Fix issue 213
  gap/oper.gi
  tst/standard/oper.tst
Labels: bug, minor

#216 Fix issue 215
  gap/labels.gd
  gap/labels.gi
  gap/oper.gi
  tst/standard/labels.tst
  tst/standard/oper.tst
Labels: bugfix, minor

#219 travis: fix conda
  .travis.yml
Labels: ci, minor
