Repository digraphs/Digraphs, pull requests merged in 2020-11, with the labels that each got.

#342 Implement initial GitHub actions support for CI
  .github/workflows/GAP.yml
  tst/testall.g
Labels: ci

#348 ci: use azure pipelines
  .travis.yml
  PackageInfo.g
  README.md
  azure-gap.sh
  azure-pipelines.yml
  ci/azure-gap.sh
  ci/coverage.py
  ci/docker-test.sh
  scripts/travis-build-dependencies.sh
  scripts/travis-build-digraphs.sh
Labels: ci

#349 Remove links to gap-packages/Digraphs
  CHANGELOG.md
  PackageInfo.g
  README.md
  doc/z-chap1.xml
  gap/oper.gi
  gap/utils.gi
Labels: minor

#352 Create a .codecov.yml file to configure Codecov
  .codecov.yml
Labels: ci

#347 Small improvements to IsSymmetricDigraph
  gap/prop.gi
  tst/standard/prop.tst
Labels: minor, performance

#346 Don't copy an immutable digraph when adding zero vertices
  doc/oper.xml
  gap/oper.gi
  tst/standard/oper.tst
Labels: minor, performance

#333 CollapseMultipleEdges
  gap/isomorph.gd
  gap/isomorph.gi
  tst/standard/isomorph.tst
Labels: performance

#359 Release candidate for v1.3.1
  .VERSION
  CHANGELOG.md
  PackageInfo.g
  VERSIONS
Labels: release-candidate
