Repository digraphs/Digraphs, pull requests merged in 2020-01, with the labels that each got.

#281 kernel: optimize OutNeighbours
  src/digraphs.c
Labels: enhancement

#278 Make bliss return the size of the automorphism group
  extern/bliss-0.73/bignum.hh
  extern/bliss-0.73/bliss_C.cc
  extern/bliss-0.73/bliss_C.h
  extern/bliss-0.73/graph.hh
  gap/isomorph.gi
  src/digraphs.c
  tst/extreme/isomorph.tst
  tst/standard/oper.tst
Labels: new-feature

#285 Allow user to specify automorphisms in HomomorphismDigraphsFinder
  doc/grahom.xml
  doc/isomorph.xml
  gap/grahom.gd
  gap/grahom.gi
  gap/isomorph.gd
  gap/isomorph.gi
  src/digraphs.c
  src/homos-graphs.c
  src/homos-graphs.h
  src/homos.c
  src/perms.c
  src/perms.h
  tst/standard/grahom.tst
  tst/standard/isomorph.tst
Labels: new-feature

#283 Allow specifying vertex colours in IsDigraphHomomorphism etc.
  doc/grahom.xml
  doc/isomorph.xml
  doc/z-chap6.xml
  gap/grahom.gd
  gap/grahom.gi
  gap/isomorph.gi
Labels: new-feature

#290 Fix bug in digraph homom. finder
  src/homos-graphs.c
Labels: bugfix

#291 Release candidate for v1.1.1
  .VERSION
  CHANGELOG.md
  PackageInfo.g
  VERSIONS
Labels: release-candidate

#271 Improve String method for a digraph, to give shorter strings
  doc/io.xml
  doc/z-chap9.xml
  gap/digraph.gi
  tst/standard/digraph.tst
  tst/standard/display.tst
Labels: new-feature
