Repository digraphs/Digraphs, pull requests merged in 2020-12, with the labels that each got.

#371 Fix doc for DotSymmetric*ColoredDigraph
  doc/display.xml
Labels: doc, minor

#364 Simplify the code coverage script
  ci/coverage.py
Labels: ci

#354 Add ModularProduct
  doc/oper.xml
  gap/oper.gd
  gap/oper.gi
  tst/standard/oper.tst
Labels: new-feature

#376 Resolve Issue #367
  src/digraphs.c
  src/digraphs.h
  src/homos.c
  tst/testinstall.tst
Labels: bugfix

#377 io: always close files (resolves Issue #374)
  doc/io.xml
  gap/io.gi
  tst/standard/io.tst
Labels: bugfix

#378 Resolve Issue #366
  doc/grape.xml
  doc/orbits.xml
  gap/grape.gi
  tst/standard/grape.tst
  tst/standard/oper.tst
Labels: bugfix
