Repository digraphs/Digraphs, pull requests merged in 2021-03, with the labels that each got.

#385 Add vertex & edge labels to Cayley digraphs
  doc/grape.xml
  gap/grape.gi
  tst/standard/grape.tst
Labels: enhancement

#421 Fix issue 368 (document edge-addition-planarity-suite in manual)
  doc/digraphs.bib
  doc/z-chap0.xml
  doc/z-chap5.xml
Labels: doc

#429 Update GitHub actions integration
  .github/workflows/gap.yml
  .github/workflows/lint.yml
  Makefile.am
  etc/cpplint.sh
  etc/gaplint.sh
Labels: ci

#336 Add Tarjan and Lengauer's (almost) linear time dominators algorithm
  PackageInfo.g
  doc/digraphs.bib
  doc/oper.xml
  doc/z-chap4.xml
  gap/oper.gd
  gap/oper.gi
  tst/standard/oper.tst
Labels: merge-in-to-master, new-feature

#420 Resolve Issue #320 (Doc config options)
  README.md
  doc/z-chap1.xml
Labels: doc

#435 Fix CI: get latest package versions slightly more robustly, via the GitHub API
  ci/docker-test.sh
  scripts/travis-build-dependencies.sh
Labels: ci

#424 Star graph
  doc/examples.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  tst/standard/examples.tst
Labels: new-feature

#425 Knightsgraph
  doc/examples.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  tst/standard/examples.tst
Labels: new-feature

#408 Add HaarGraph
  doc/examples.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  gap/utils.gd
  gap/utils.gi
  tst/standard/examples.tst
Labels: new-feature

#416 Add GridGraph
  doc/examples.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  tst/standard/examples.tst
Labels: new-feature

#409 Add KingsGraph
  doc/examples.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  tst/standard/examples.tst
Labels: new-feature

#417 Add LollipopGraph
  doc/examples.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  oper.gi
  tst/standard/examples.tst
Labels: new-feature

#411 Add BananaTree
  doc/examples.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  tst/standard/examples.tst
Labels: new-feature

#423 Add TadpoleDigraph
  doc/examples.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  tst/standard/examples.tst
Labels: new-feature

#442 display: simplify some `Dot...` methods, and use StringFormatted
  gap/display.gi
Labels: minor

#440 ViewString: special case for trees and forests
  doc/attr.xml
  doc/examples.xml
  doc/oper.xml
  gap/attr.gi
  gap/digraph.gi
  gap/prop.gd
  tst/standard/attr.tst
  tst/standard/examples.tst
Labels: enhancement, merge-in-to-master, minor

#437 Fix DigraphCore
  gap/attr.gi
  tst/standard/attr.tst
Labels: bugfix, major

#441 Add DigraphCycle as a synonym for CycleDigraph
  doc/examples.xml
  gap/examples.gd
  tst/standard/examples.tst
Labels: enhancement, merge-in-to-master, minor

#446 Improve ChromaticNumber with Brooks' theorem
  gap/attr.gi
  tst/standard/attr.tst
Labels: minor, performance

#448 Set `IsSymmetricDigraph` to `true` for digraphs created from Graph6/Sparse6 strings
  doc/constructors.xml
  doc/io.xml
  doc/isomorph.xml
  gap/io.gi
  tst/extreme/grahom.tst
  tst/extreme/isomorph.tst
  tst/standard/attr.tst
  tst/standard/cliques.tst
  tst/standard/examples.tst
  tst/standard/grahom.tst
  tst/standard/io.tst
  tst/standard/oper.tst
  tst/standard/prop.tst
  tst/testinstall.tst
Labels: enhancement, minor

#447 Improve ViewStrings/TrueMethods for tournaments/cycle digraphs
  gap/digraph.gi
  gap/examples.gi
  gap/prop.gd
  gap/prop.gi
Labels: enhancement, merge-in-to-master, minor, performance

#404 Named graphs architecture
  data/named-digraphs-main-database.g
  data/named-digraphs-test-database.g
  doc/digraph.xml
  doc/z-chap2.xml
  gap/digraph.gd
  gap/digraph.gi
  tst/extreme/named.tst
  tst/standard/digraph.tst
Labels: new-feature
