Repository digraphs/Digraphs, pull requests merged in 2021-02, with the labels that each got.

#397 Test against GAP stable-4.10 on GitHub Actions
  .github/workflows/ci.yml
Labels: ci

#395 Be consistent about authors/contributors in the documentation
  doc/z-chap0.xml
  doc/z-title.xml
Labels: doc, minor

#410 Attempt to fix the GitHub Actions linting job
  .github/workflows/ci.yml
Labels: ci

#361 Maximal common subdigraph/Minimal common superdigraph
  doc/grahom.xml
  doc/z-chap6.xml
  gap/grahom.gd
  gap/grahom.gi
  tst/standard/grahom.tst
Labels: new-feature
