Repository digraphs/Digraphs, pull requests merged in 2021-06, with the labels that each got.

#488 build: update autotools
  configure.ac
  extern/edge-addition-planarity-suite-Version_3.0.1.0/Makefile.am
  extern/edge-addition-planarity-suite-Version_3.0.1.0/configure.ac
Labels: minor

#490 examples: add binary tree
  doc/examples.xml
  doc/main.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  gap/utils.gd
  gap/utils.gi
  tst/standard/examples.tst
Labels: minor, new-feature

#456 Add `StackedBookGraph`
  doc/examples.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  tst/standard/examples.tst
Labels: hackathon-may-2021, new-feature
