Repository digraphs/Digraphs, pull requests merged in 2021-05, with the labels that each got.

#466 Remove .appveyor.yml
  .appveyor.yml
Labels: ci

#469 Run GitHub Actions tests on a daily schedule, and allow jobs to be started manually too
  .github/workflows/gap.yml
  .github/workflows/lint.yml
Labels: ci

#462 Fix `DigraphMaximumMatching` for digraphs with custom vertex labels
  gap/attr.gi
  tst/standard/attr.tst
Labels: bugfix

#468 Stop the 'combination operations' from changing their given list of digraphs
  gap/oper.gi
  tst/standard/oper.tst
Labels: bugfix

#452 Fix the edge labels of Cayley digraphs
  gap/grape.gi
  tst/standard/grape.tst
Labels: bugfix

#471 Enable the manual to be compiled without loading Digraphs
  PackageInfo.g
  ci/docker-test.sh
  gap/doc.g
  gap/utils.gi
  makedoc.g
  read.g
  tst/testall.g
Labels: doc

#473 CI: refactor the CI a bit, and add a macOS job
  .github/workflows/gap.yml
Labels: ci

#476 GitHub Actions CI: add a 32-bit job
  .github/workflows/gap.yml
Labels: ci

#477 Add `tst/teststandard.g` and use it as the `PackageInfo.g` testfile
  PackageInfo.g
  tst/teststandard.g
Labels: tests

#475 Add a `.release` helper script for the release system
  .release
Labels: minor

#481 GitHub Actions: have separate workflow file for manual
  .github/workflows/gap.yml
  .github/workflows/manual.yml
Labels: ci

#483 Split the four test functions into different steps in GitHub Actions
  .github/workflows/gap.yml
  tst/github_actions/examples.g
  tst/github_actions/extreme.g
  tst/github_actions/install.g
  tst/github_actions/standard.g
Labels: ci

#486 Renamed three functions for consistency
  doc/examples.xml
  doc/z-chap2.xml
  gap/examples.gd
  gap/examples.gi
  tst/standard/examples.tst
Labels: hackathon-may-2021

#382 Add Lawler and Byskov's dynamic programming algorithms for chromatic number
  doc/attr.xml
  doc/digraphs.bib
  gap/attr.gi
  init.g
  tst/standard/attr.tst
Labels: hackathon-may-2021, new-feature
