Repository digraphs/Digraphs, pull requests merged in 2021-01, with the labels that each got.

#380 Correct some capitalisation in the manual
  doc/attr.xml
  doc/oper.xml
Labels: doc, minor

#379 Add VerticesReachableFrom
  doc/oper.xml
  doc/z-chap4.xml
  gap/oper.gd
  gap/oper.gi
  tst/standard/oper.tst
Labels: merge-in-to-master, new-feature

#387 Release candidate for v1.4.0
  .VERSION
  CHANGELOG.md
  PackageInfo.g
  VERSIONS
Labels: release-candidate
