Repository digraphs/Digraphs, pull requests merged in 2022-01, with the labels that each got.

#375 Add checks for upper/lower semimodular lattices
  doc/attr.xml
  doc/prop.xml
  doc/z-chap4.xml
  doc/z-chap5.xml
  gap/attr.gd
  gap/attr.gi
  tst/standard/attr.tst
Labels: new-feature, merge-in-to-master

#525 CI: use codecov-action@v2 instead of @v1
  .github/workflows/gap.yml
Labels: ci

#526 digraph: add AsDigraph for partial perms and fix doc
  doc/digraph.xml
  gap/digraph.gd
  gap/digraph.gi
  tst/standard/digraph.tst
Labels: doc, new-feature

#464 Add GitHub Actions Windows tests
  .gitattributes
  .github/workflows/gap.yml
Labels: ci, windows
