Repository digraphs/Digraphs, pull requests merged in 2022-12, with the labels that each got.

#567 ci: change master to main on azure
  azure-pipelines.yml
Labels: ci

#566 Rewrite buildsystem to use Makefile.gappkg
  .gitignore
  Makefile.am
  Makefile.gappkg
  Makefile.in
  autogen.sh
  ci/docker-test.sh
  configure.ac
  m4/ax_check_bliss.m4
  m4/ax_check_planarity.m4
  m4/ax_code_coverage.m4
  src/CPPLINT.cfg
  src/cliques.c
Labels: build-system

#569 Fix some typos found by codespell
  CHANGELOG.md
  doc/constructors.xml
  doc/display.xml
  doc/isomorph.xml
  doc/oper.xml
  doc/prop.xml
  doc/z-chap9.xml
  gap/attr.gi
  gap/digraph.gi
  gap/grahom.gi
  gap/io.gi
  gap/prop.gi
  src/cliques.c
  src/digraphs.c
  src/homos.c
  tst/standard/cliques.tst
  tst/standard/grahom.tst
  tst/standard/io.tst
  tst/standard/isomorph.tst
Labels: enhancement
