Repository digraphs/Digraphs, pull requests merged in 2023-04, with the labels that each got.

#578 Change test that relies on xpdf not being installed
  tst/standard/display.tst
Labels: tests

#583 Add immediate methods for connected and strongly connected graphs
  gap/prop.gi
  tst/standard/prop.tst
Labels: enhancement, minor

#582 Standardise the way that `UndirectedSpanningForest` works in relation to mutability
  gap/attr.gi
Labels: minor, technical
