Repository digraphs/Digraphs, pull requests merged in 2024-05, with the labels that each got.

#642 Update for gaplint 1.2.0
  gap/digraph.gi
  tst/standard/oper.tst
Labels: ci, lint

#646 Merge CI changes from stable-1.7 into main
  .github/workflows/gap.yml
Labels: ci

#648 Fix compile warnings
  configure.ac
  extern/bliss-0.73/bliss_C.cc
  extern/bliss-0.73/defs.cc
  extern/bliss-0.73/graph.cc
  extern/bliss-0.73/timer.cc
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDFSUtils.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDrawPlanar.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDrawPlanar_Extensions.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphEmbed.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphExtensions.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphFunctionTable.h
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphIO.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphIsolator.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK23Search.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK23Search_Extensions.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK33Search.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK33Search_Extensions.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK4Search.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK4Search_Extensions.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphOuterplanarObstruction.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphTests.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphUtils.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planarity.h
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planarityRandomGraphs.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planaritySpecificGraph.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planarityUtils.c
  src/bliss-includes.h
  src/digraphs.c
  src/gap-includes.h
  src/planar.c
Labels: C language

#641 Refactor CI
  .github/actions/test_with_valgrind/action.yml
  .github/workflows/codespell.yml
  .github/workflows/config_options.yml
  .github/workflows/gap.yml
  .github/workflows/lint.yml
  .github/workflows/manual.yml
  .github/workflows/os.yml
  .github/workflows/ubuntu.yml
  .github/workflows/valgrind.yml
  azure-pipelines.yml
  ci/azure-gap.sh
  ci/coverage.py
  ci/docker-test.sh
  environment.yml
  src/cliques.c
Labels: ci

#650 Edge-weights #3: minimum spanning trees
  doc/weights.xml
  doc/z-chap5.xml
  gap/weights.gd
  gap/weights.gi
  tst/standard/weights.tst
  tst/testinstall.tst
Labels: new-feature

#652 weights.gi: correct whitespace
  gap/weights.gi
Labels: minor, lint
