Repository digraphs/Digraphs, pull requests merged in 2024-03, with the labels that each got.

#623 Revert "build(deps): bump codecov/codecov-action from 3 to 4"
  .github/workflows/gap.yml
Labels: ci, dependencies

#610 DigraphCycleBasis
  doc/oper.xml
  doc/z-chap4.xml
  gap/oper.gd
  gap/oper.gi
  tst/standard/oper.tst
Labels: new-feature

#630 ci: try to fix datastructures
  .github/workflows/gap.yml
Labels: ci

#631 ci: add GAP 4.13
  .github/workflows/gap.yml
Labels: ci

#633 Fix compiler warnings
  configure.ac
  extern/bliss-0.73/bliss_C.cc
  extern/bliss-0.73/defs.cc
  extern/bliss-0.73/graph.cc
  extern/bliss-0.73/timer.cc
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDFSUtils.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDrawPlanar.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDrawPlanar_Extensions.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphEmbed.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphFunctionTable.h
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphIO.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphIsolator.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK23Search.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK23Search_Extensions.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK33Search.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK33Search_Extensions.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK4Search.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphK4Search_Extensions.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphOuterplanarObstruction.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphTests.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphUtils.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planarity.h
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planarityRandomGraphs.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planaritySpecificGraph.c
  extern/edge-addition-planarity-suite-Version_3.0.1.0/c/planarityUtils.c
  src/bitarray.c
  src/bitarray.h
  src/bliss-includes.h
  src/cliques.c
  src/cliques.h
  src/conditions.h
  src/digraphs.c
  src/digraphs.h
  src/gap-includes.h
  src/homos-graphs.c
  src/homos-graphs.h
  src/homos.c
  src/homos.h
  src/perms.h
  src/planar.c
  src/planar.h
  src/schreier-sims.c
Labels: refactor
